# Generated by Django 6.1.1 on 2026-09-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='ejemplo',
        ),
        migrations.RemoveField(
            model_name='tipoia',
            name='ejemplo',
        ),
    ]
